import type { Inquiry } from '@/lib/server/inquiry';
import { destinations } from '@/lib/content';

const esc = (value: string) => value.replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' })[character] || character);
const line = (label: string, value: string | number | boolean) => `<tr><th style="text-align:left;padding:7px 12px 7px 0;color:#184A25">${esc(label)}</th><td style="padding:7px 0">${esc(String(value))}</td></tr>`;
const serverEnv = () => (globalThis as unknown as { process?: { env?: Record<string, string | undefined> } }).process?.env || {};
function details(inquiry: Inquiry, reference: string) { const chosen = inquiry.destinations.map((slug) => destinations.find((destination) => destination.slug === slug)?.name).filter(Boolean).join(', ') || 'Please recommend an itinerary'; return `<table style="font-family:Arial,sans-serif;font-size:14px;line-height:1.5;border-collapse:collapse">${line('Reference', reference)}${line('Name', inquiry.fullName)}${line('Country', inquiry.country)}${line('Email', inquiry.email)}${line('Phone / WhatsApp', inquiry.phone)}${line('Arrival', inquiry.arrivalDate.toISOString().slice(0,10))}${line('Departure', inquiry.departureDate.toISOString().slice(0,10))}${line('Adults', inquiry.adults)}${line('Children', inquiry.children)}${line('Selected destinations', chosen)}${line('Interests', inquiry.interests.join(', ') || 'Not specified')}${line('Accommodation', inquiry.accommodation)}${line('Airport pickup', inquiry.airportPickup ? 'Required' : 'Not required')}${line('Special requirements', inquiry.specialRequirements || 'None')}<tr><th style="text-align:left;padding:7px 12px 7px 0;color:#184A25;vertical-align:top">Message</th><td style="padding:7px 0;white-space:pre-wrap">${esc(inquiry.message)}</td></tr></table>`; }
async function send(payload: object) { const environment = serverEnv(); const token = environment.ZEPTOMAIL_SEND_MAIL_TOKEN; const url = environment.ZEPTOMAIL_API_URL || 'https://api.zeptomail.com/v1.1/email'; if (!token) throw new Error('Mail service is not configured.'); const response = await fetch(url, { method: 'POST', headers: { Authorization: `Zoho-enczapikey ${token}`, 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); if (!response.ok) throw new Error('Mail service rejected the message.'); }
export async function sendInquiryEmails(inquiry: Inquiry, reference: string) { const environment = serverEnv(); const from = { address: environment.MAIL_FROM_ADDRESS || '', name: environment.MAIL_FROM_NAME || 'Chauffeur Emil Lanka Tours' }; const recipient = environment.INQUIRY_RECIPIENT; if (!from.address || !recipient) throw new Error('Mail sender is not configured.'); const sender = { from, to: [{ email_address: { address: recipient } }], reply_to: [{ address: inquiry.email, name: inquiry.fullName }], subject: `[${reference}] New Sri Lanka Tour Request — ${inquiry.fullName}`, htmlbody: `<h1 style="font-family:Arial;color:#184A25">New Sri Lanka Tour Request</h1>${details(inquiry, reference)}` }; const guest = { from, to: [{ email_address: { address: inquiry.email, name: inquiry.fullName } }], subject: `We received your Sri Lanka tour request — ${reference}`, htmlbody: `<div style="font-family:Arial,sans-serif;line-height:1.6;color:#102318"><h1 style="color:#184A25">Tour Request Received</h1><p>Dear ${esc(inquiry.fullName)},</p><p>Thank you for contacting Chauffeur Emil Lanka Tours. Emil will review your request and contact you personally.</p><p><strong>Reference:</strong> ${esc(reference)}<br><strong>Arrival:</strong> ${inquiry.arrivalDate.toISOString().slice(0,10)}<br><strong>Departure:</strong> ${inquiry.departureDate.toISOString().slice(0,10)}<br><strong>Travellers:</strong> ${inquiry.adults} adults${inquiry.children ? `, ${inquiry.children} children` : ''}</p><p>Please keep this reference for future communication. This acknowledgement is not a booking confirmation.</p></div>` }; await send(sender); await send(guest); }
